version: '3'
services:
  pkappa2:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./docker_data:/data
      - ./filters:/app/filters
    restart: unless-stopped
    environment:
      # Change values in .env file
      PKAPPA2_USER_PASSWORD: ${PKAPPA2_USER_PASSWORD}
      PKAPPA2_PCAP_PASSWORD: ${PKAPPA2_PCAP_PASSWORD}
