name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.18' ]
        node: [ 19, 18 ]
        exclude:
          - go: 1.19
            node: 18
          - go: 1.18
            node: 19
    name: Go ${{ matrix.go }}, Node ${{ matrix.node }} build
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'
        cache-dependency-path: 'web/yarn.lock'

    - name: Build frontend
      working-directory: ./web
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        cache: true
    
    - name: Install dependencies
      run: sudo apt-get install -y libpcap-dev

    - name: Build
      run: go build -v ./cmd/pkappa2/main.go
